# Generated by Django 2.2.28 on 2022-12-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('macType', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MachineStatus',
            fields=[
                ('macId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('line', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'NG'), (1, 'OK'), (2, 'SETTING')], default=1)),
                ('buildConfig', models.CharField(blank=True, max_length=10, null=True)),
                ('lotId', models.CharField(default='', max_length=30)),
                ('curDetail', models.CharField(blank=True, max_length=1000, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sw', models.CharField(blank=True, max_length=30, null=True)),
                ('macType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.MachineType')),
            ],
        ),
    ]
