# Generated by Django 2.2.28 on 2022-12-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20221205_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinestatus',
            name='macType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='reminder.MachineType'),
        ),
    ]
