# Generated by Django 2.2.28 on 2022-12-09 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder', '0003_auto_20221206_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestatus',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
