# Generated by Django 2.2.28 on 2022-12-09 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder', '0005_remove_machinestatus_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_mac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.MachineStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
