# Generated by Django 2.2.28 on 2022-12-09 07:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder', '0006_user_mac'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_mac',
            unique_together={('macId', 'user')},
        ),
    ]
